/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateTransactionInput {
  'status' : TransactionStatus,
  'beneficiaryName' : string,
  'date' : string,
  'note' : [] | [string],
  'role' : string,
  'bankName' : string,
  'amountEur' : bigint,
  'maskedAccount' : string,
}
export interface Transaction {
  'id' : TransactionId,
  'status' : TransactionStatus,
  'beneficiaryName' : string,
  'date' : string,
  'note' : [] | [string],
  'role' : string,
  'bankName' : string,
  'amountEur' : bigint,
  'maskedAccount' : string,
}
export type TransactionId = number;
export interface TransactionPage {
  'title' : string,
  'pageNote' : [] | [string],
  'sectionFootnote' : [] | [string],
  'transactions' : Array<Transaction>,
}
export type TransactionStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTransaction' : ActorMethod<[CreateTransactionInput], TransactionId>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransaction' : ActorMethod<[TransactionId], [] | [Transaction]>,
  'getTransactionPages' : ActorMethod<[], Array<TransactionPage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTransactionFailed' : ActorMethod<[TransactionId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTransaction' : ActorMethod<
    [TransactionId, CreateTransactionInput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];