/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const CreateTransactionInput = IDL.Record({
  'status' : TransactionStatus,
  'beneficiaryName' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'role' : IDL.Text,
  'bankName' : IDL.Text,
  'amountEur' : IDL.Nat,
  'maskedAccount' : IDL.Text,
});
export const TransactionId = IDL.Nat32;
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'beneficiaryName' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'role' : IDL.Text,
  'bankName' : IDL.Text,
  'amountEur' : IDL.Nat,
  'maskedAccount' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TransactionPage = IDL.Record({
  'title' : IDL.Text,
  'pageNote' : IDL.Opt(IDL.Text),
  'sectionFootnote' : IDL.Opt(IDL.Text),
  'transactions' : IDL.Vec(Transaction),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTransaction' : IDL.Func([CreateTransactionInput], [TransactionId], []),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransaction' : IDL.Func(
      [TransactionId],
      [IDL.Opt(Transaction)],
      ['query'],
    ),
  'getTransactionPages' : IDL.Func([], [IDL.Vec(TransactionPage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTransactionFailed' : IDL.Func([TransactionId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTransaction' : IDL.Func(
      [TransactionId, CreateTransactionInput],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const CreateTransactionInput = IDL.Record({
    'status' : TransactionStatus,
    'beneficiaryName' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'bankName' : IDL.Text,
    'amountEur' : IDL.Nat,
    'maskedAccount' : IDL.Text,
  });
  const TransactionId = IDL.Nat32;
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'beneficiaryName' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'bankName' : IDL.Text,
    'amountEur' : IDL.Nat,
    'maskedAccount' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TransactionPage = IDL.Record({
    'title' : IDL.Text,
    'pageNote' : IDL.Opt(IDL.Text),
    'sectionFootnote' : IDL.Opt(IDL.Text),
    'transactions' : IDL.Vec(Transaction),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTransaction' : IDL.Func(
        [CreateTransactionInput],
        [TransactionId],
        [],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransaction' : IDL.Func(
        [TransactionId],
        [IDL.Opt(Transaction)],
        ['query'],
      ),
    'getTransactionPages' : IDL.Func([], [IDL.Vec(TransactionPage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTransactionFailed' : IDL.Func([TransactionId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTransaction' : IDL.Func(
        [TransactionId, CreateTransactionInput],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };